eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    instance-id: ${eureka.instance.ip-address}:${server.port}
    prefer-ip-address: true
    ip-address: 127.0.0.1
spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
# 配置监控的接口给 spring-boot-admin监控
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
info:
  version: 1.0.0
# 熔断器配置
resilience4j:
  circuitbreaker:
    configs:
      #  配置默认配置
      default:
        slidingWindowSize: 100
        permittedNumberOfCallsInHalfOpenState: 10
        waitDurationInOpenState: 10000
        failureRateThreshold: 60
        eventConsumerBufferSize: 10
        registerHealthIndicator: true
    instances:
      backendA:
        # 引用默认配置
        baseConfig: default
        waitDurationInOpenState: 5000