spring:
  cloud:
    gateway:
      default-filters:
        - StripPrefix=1
      routes:
        - id: mq-service
          uri: http://localhost:8888
          predicates:
            - Path=/mq-service
        - id: solr-service
          uri: http://localhost:8890
          predicates:
            - Path=/solr-service
  application:
    name: gateway-service
server:
  port: 8083
test: 1sdf
