server:
  port: 8888
spring:
  cloud:
    stream:
      kafka:
        binder:
          auto-add-partitions: true
          transaction:
            producer:
              partition-count: 3
      bindings:
        WTON_TEST:
          consumer:
            batch-mode: true
  kafka:
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: '*'
      fetch-max-wait: 500
      max-poll-records: 1000
  application:
    name: mq-service
