
export const INIT_WEBSOCKET = "INIT_WEBSOCKET";
export const SET_MESSAGE = "SET_MESSAGE";
export const SET_USERLIST = 'SET_USERLIST';
export const SET_PRIVATE_MESSAGE='SET_PRIVATE_MESSAGE'
export const MDZZ = "MDZZ"
